language: java
sudo: false
notifications:
    webhooks: https://www.travisbuddy.com/
addons:
  sonarcloud:
    organization: "apreto"
script:
  - mvn clean test sonar:sonar -Pcoverage -Dsonar.projectKey=apreto_datagencli
